from qdrant_client import QdrantClient
from qdrant_client.http.models import Distance, VectorParams, PointStruct, Filter, FieldCondition, MatchValue
from typing import List, Dict, Any, Optional
import numpy as np
import uuid

class SolidStateWiki:
    """
    Hierarchical Vector Database representing the digital twin's memory.
    It separates raw 'episodic' experiences from consolidated 'semantic' abstractions.
    """
    def __init__(self, host: str = "localhost", port: int = 6333):
        self.client = QdrantClient(host=host, port=port)
        self.episodic_collection = "episodic_memory"
        self.semantic_collection = "semantic_memory"
        
        self._ensure_collection_exists(self.episodic_collection, vector_size=256) 
        self._ensure_collection_exists(self.semantic_collection, vector_size=256)

    def _ensure_collection_exists(self, collection_name: str, vector_size: int):
        try:
            collections = self.client.get_collections().collections
            exists = any(c.name == collection_name for c in collections)
            
            if not exists:
                self.client.create_collection(
                    collection_name=collection_name,
                    vectors_config=VectorParams(size=vector_size, distance=Distance.COSINE),
                )
        except Exception as e:
            print(f"Warning: Could not connect to Qdrant to ensure collection {collection_name} exists: {e}")

    def store_episodic(self, parameters: np.ndarray, metadata: Dict[str, Any] = None) -> str:
        """
        Stores a raw, time-bound parameter extraction from direct ingestion.
        """
        point_id = str(uuid.uuid4())
        point = PointStruct(
            id=point_id,
            vector=parameters.tolist(),
            payload=metadata or {}
        )
        self.client.upsert(collection_name=self.episodic_collection, points=[point])
        return point_id

    def store_semantic(self, parameters: np.ndarray, metadata: Dict[str, Any] = None) -> str:
        """
        Stores a consolidated, abstract concept generated by the reflection loop.
        """
        point_id = str(uuid.uuid4())
        point = PointStruct(
            id=point_id,
            vector=parameters.tolist(),
            payload=metadata or {}
        )
        self.client.upsert(collection_name=self.semantic_collection, points=[point])
        return point_id

    def retrieve_similar(self, query_vector: np.ndarray, collection: str, limit: int = 5, min_score: float = 0.0) -> List[Any]:
        """
        Retrieves the most mathematically similar parameters from a specific hierarchy.
        """
        results = self.client.search(
            collection_name=collection,
            query_vector=query_vector.tolist(),
            limit=limit,
            score_threshold=min_score
        )
        return results

    def fetch_all_episodic(self, limit: int = 1000) -> tuple[List[np.ndarray], List[Dict[str, Any]]]:
        """
        Fetches a batch of raw episodic memories for the reflection/clustering loop.
        """
        # Scroll through episodic memory. In production, we would filter by a 'processed' boolean
        # to only pull new episodes since the last dream state.
        res = self.client.scroll(
            collection_name=self.episodic_collection,
            limit=limit,
            with_vectors=True
        )
        points = res[0]
        vectors = [np.array(p.vector) for p in points]
        payloads = [p.payload for p in points]
        return vectors, payloads
